begin;
select plan(22);
select has_table('public','proposal_attachments','draft attachments exist');
select has_table('public','proposal_version_attachments','version attachment references exist');
select has_column('public','proposal_attachments','checksum_sha256','attachments keep sha256');
select has_column('public','proposal_version_attachments','checksum_sha256','version references freeze sha256');
select has_function('public','prepare_proposal_attachment',array['uuid','text','text','bigint','text'],'attachment preparation RPC exists');
select has_function('public','remove_proposal_attachment',array['uuid'],'attachment removal RPC exists');
select isnt_empty($$select 1 from pg_class where oid='public.proposal_attachments'::regclass and relrowsecurity$$,'attachments use RLS');
select isnt_empty($$select 1 from pg_class where oid='public.proposal_version_attachments'::regclass and relrowsecurity$$,'version attachments use RLS');
select is_empty($$select 1 from information_schema.role_table_grants where table_schema='public' and table_name='proposal_attachments' and grantee='anon'$$,'anon has no attachment grants');
select is_empty($$select 1 from information_schema.role_table_grants where table_schema='public' and table_name='proposal_attachments' and grantee='authenticated' and privilege_type in('INSERT','UPDATE','DELETE')$$,'authenticated has no direct attachment DML');
select is_empty($$select 1 from information_schema.role_table_grants where table_schema='public' and table_name='proposal_version_attachments' and grantee='authenticated' and privilege_type in('INSERT','UPDATE','DELETE')$$,'version references are append-only to clients');
select isnt_empty($$select 1 from information_schema.role_routine_grants where routine_schema='public' and routine_name='prepare_proposal_attachment' and grantee='authenticated'$$,'authenticated can call preparation RPC');
select isnt_empty($$select 1 from pg_constraint where conname='proposal_attachments_proposal_fk'$$,'attachment tenant FK exists');
select isnt_empty($$select 1 from pg_constraint where conname='proposal_version_attachments_version_fk'$$,'version tenant FK exists');
select isnt_empty($$select 1 from pg_constraint where conname='proposal_version_attachments_attachment_fk'$$,'attachment reference tenant FK exists');
select isnt_empty($$select 1 from pg_trigger where tgname='proposal_versions_freeze_attachments' and not tgisinternal$$,'version creation freezes attachments');
select isnt_empty($$select 1 from storage.buckets where id='proposal-attachments' and not public and file_size_limit=10485760$$,'private bucket has ten megabyte limit');
select is((select allowed_mime_types from storage.buckets where id='proposal-attachments'),array['application/pdf','image/png','image/jpeg']::text[],'bucket MIME allowlist is conservative');
select is((select count(*)::integer from pg_policies where schemaname='storage' and tablename='objects' and policyname like 'proposal members%'),3,'storage has three scoped policies');
select isnt_empty($$select 1 from pg_proc where proname='prepare_proposal_attachment' and prosecdef and proconfig @> array['search_path=""']$$,'prepare RPC has empty search path');
select isnt_empty($$select 1 from pg_proc where proname='remove_proposal_attachment' and prosecdef and proconfig @> array['search_path=""']$$,'remove RPC has empty search path');
select isnt_empty($$select 1 from pg_constraint where conname='audit_logs_action_catalog' and pg_get_constraintdef(oid) like '%proposal.version_pdf_generated%'$$,'audit catalog contains PDF event');
select * from finish();
rollback;
