begin;
select plan(18);
select has_table('public','proposal_templates','templates exist');
select has_table('public','proposal_template_sections','template sections exist');
select has_table('public','proposal_template_items','template items exist');
select has_table('public','proposal_template_versions','template versions exist');
select has_table('public','proposal_versions','proposal versions exist');
select has_column('public','proposals','source_template_id','proposal keeps template origin');
select has_column('public','proposals','source_template_version','proposal keeps template version');
select has_function('public','create_proposal_template',array['text','text'],'template creation is exposed');
select has_function('public','create_proposal_from_template',array['uuid','uuid','text','date','uuid'],'atomic proposal copy is exposed');
select has_function('public','create_proposal_version',array['uuid','uuid'],'proposal snapshot is exposed');
select has_function('public','create_proposal_template_version',array['uuid','uuid'],'template snapshot is exposed');
select isnt_empty($$select 1 from pg_class where oid='public.proposal_templates'::regclass and relrowsecurity$$,'templates use RLS');
select isnt_empty($$select 1 from pg_class where oid='public.proposal_versions'::regclass and relrowsecurity$$,'versions use RLS');
select isnt_empty($$select 1 from pg_constraint where conname='proposal_versions_number_key'$$,'proposal version number is unique');
select isnt_empty($$select 1 from pg_constraint where conname='proposal_versions_request_key'$$,'proposal requests are idempotent');
select is_empty($$select 1 from information_schema.role_table_grants where table_schema='public' and table_name='proposal_versions' and grantee='authenticated' and privilege_type in('INSERT','UPDATE','DELETE')$$,'versions are append-only to clients');
select is_empty($$select 1 from information_schema.role_table_grants where table_schema='public' and table_name='proposal_template_versions' and grantee='authenticated' and privilege_type in('INSERT','UPDATE','DELETE')$$,'template versions are append-only to clients');
select isnt_empty($$select 1 from information_schema.role_routine_grants where routine_schema='public' and routine_name='create_proposal_version' and grantee='authenticated'$$,'authenticated can execute version RPC');
select * from finish();
rollback;
