import { createClient } from "../supabase/server";

// The local schema types are regenerated by `npm run supabase:types` when Docker is available.
// This narrow adapter keeps D1 callers typed without weakening the generated client globally.
export async function createProposalsDb() {
  const client = await createClient();
  type Result = { data: unknown; error: { message: string } | null };
  type Query = PromiseLike<Result> & {
    select(columns?: string, options?: { count?: "exact" }): Query;
    eq(column: string, value: unknown): Query;
    ilike(column: string, pattern: string): Query;
    in(column: string, values: readonly string[]): Query;
    order(column: string, options?: { ascending?: boolean }): Query;
    range(from: number, to: number): Query;
    limit(count: number): Query;
    maybeSingle(): Promise<Result>;
    single(): Promise<Result>;
  };
  return client as unknown as {
    from(table: string): Query;
    rpc(
      name: string,
      args?: Record<string, unknown>,
    ): Promise<{ data: unknown; error: { message: string } | null }>;
  };
}
